
services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/app
    depends_on:
      - auth-db

  auth-db:
    image: postgres:16.2-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

volumes:
  auth_data: