services:
  auth-service:
    extends:
      file: docker-compose.yml
      service: auth-service
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      DEBUG: ${DEBUG:-true}
    volumes:
      - ./:/auth-service:cached
    ports:
      - "7000:7000"
  auth-db:
    extends:
      file: docker-compose.yml
      service: auth-db
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_DB: ${DB_NAME:-auth-db}
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
    ports:
      - "${DB_PORT:-5432}:5432"
