services:
  auth-service:
    extends:
      file: docker-compose.yml
      service: auth-service
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command:
      sh -c "aerich migrate && aerich upgrade &&
              uvicorn app.index:app --host 0.0.0.0 --port 1000 --reload
            "
    environment:
      DEBUG: ${DEBUG:-true}
    volumes:
      - ./:/auth-service:cached
    ports:
      - "1000:1000"
    user: "1000:1000"

  auth-db:
    extends:
      file: docker-compose.yml
      service: auth-db
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME:-auth-db}
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
    ports:
      - "${DB_PORT:-5432}:5432"