
services:
  server:
    container_name: eldorado_server
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    container_name: eldorado_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: